apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-report-streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-report-streamlit
  template:
    metadata:
      labels:
        app: test-report-streamlit
    spec:
      containers:
        - name: streamlit
          image: test-report-analyzer-streamlit:latest
          ports:
            - containerPort: 8501
