apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-report-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-report-mongo
  template:
    metadata:
      labels:
        app: test-report-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          env:
            - name: MONGO_INITDB_DATABASE
              value: test_analyzer
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
